#!/usr/bin/env bash
# Installs nginx web server

apt-get update
apt-get install -y nginx
echo "Hello World!" > /etc/nginx/html/index.html

redirect = "\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
file_ = "/etc/nginx/sites-available/default"

sed -i "39i\ $redirect" "$file_"
service nginx restart
