#!/usr/bin/env bash
# Configures a server with HAProxy

apt update -y && apt upgrade -y
apt install haproxy=1.6.\* -y

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 113819-web-01 54.210.47.110:80 check
        server 113819-web-02 54.210.47.110:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
