#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
apt-get update
apt-get install haproxy -y

printf %s "
frontend hbnb-lb_front
        bind *:80
        mode http
        default_backend hbnb-lb_back
backend hbnb-lb_back
        balance roundrobin
        server 4565-web-01 3.85.224.38:80 check
        server 4565-web-02 3.215.190.137:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy start
