#!/usr/bin/env bash
n="80 default_server"
l="8080 default_server"
sed -i "s/$l/$n/" /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
