#!/usr/bin/env bash
#This script is displaying bad luck for the 4th loop, good luck for the 8th loop, Best School for the other iterations
n=1
while [ $n -le 10 ]
do
	if [ $n == 4 ]
	then
		echo "bad luck"
	elif [ $n == 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$(( n+1 ))
done
